package com.hkbufyp.hrms.ui.navigation

sealed class Screen(val route: String, val sensitiveAuth: Boolean = false) {
    data object Login: Screen("login")
    data object Home: Screen("home")
    data object Setting: Screen("setting")
    data object ClockIn: Screen("clock-in")
    data object ApplyLeave: Screen("leave-apply")
    data object CheckLeaveBalance: Screen("leave-balance")
    data object MyLeaveApplications: Screen("leave-my-applications")
    data object MyLeaveApplicationDetail: Screen("leave-my-application-detail/{recordId}")
    data object Announcement: Screen("announcement")
    data object AnnouncementDetail: Screen("announcement/{id}")
    data object PostAnnouncement: Screen("announcement-post/{id}")
    data object ManageAnnouncement: Screen("announcement-manage")
    data object EmployeeRegistration: Screen("employee-reg")
    data object LeaveManagement: Screen("leave-management")
    data object LeaveApplicationApproval: Screen("leave-approval/{recordId}")
    data object Departments: Screen("departments")
    data object DepartmentDetail: Screen("department-detail/{departmentId}")
    data object SensitiveAuth: Screen("sensitive-auth/{originalRoute}")
    data object EmployeeManagement: Screen("employee-management")
    data object EmployeeDetail: Screen("employee-detail/{employeeId}")
    data object ClockInDevices: Screen("clock-in-devices")
    data object ClockInWifiDevices: Screen("clock-in-wifi-devices")
    data object ClockInBLEDevices: Screen("clock-in-ble-devices")
    data object WifiScanning: Screen("wifi-scanning")
    data object AttendTimeslotDetail: Screen("attend-timeslot-detail/{id}")
    data object AttendTimeslot: Screen("attend-timeslot")
    data object CustomEmployeeTimeslot: Screen("custom-employee-timeslot/{id}")
    data object SetCustomEmployeeTimeslot: Screen("set-custom-employee-timeslot")
    data object BleScanning: Screen("ble-scanning")
    data object LoginLog: Screen("log-login")
    data object AttendLog: Screen("log-attend")
    data object EmployeeManageLog: Screen("log-manage-employee")
    data object LeaveManageLog: Screen("log-manage-leave")
    data object EmployeeAttendRecord: Screen("employee-attend-record")
    data object EmployeeAttendRecordDetail: Screen("employee-attend-record-detail/{id}")
    data object ClockInMethod: Screen("clock-in-method")
}